name: Android Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Biraz daha eski ve kararlı sürüm
    steps:
    - uses: actions/checkout@v3
    
    - name: Java 11 Kurulumu
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Proje eski olduğu için 17 yerine 11 kullanıyoruz
        distribution: 'temurin'
        cache: gradle

    - name: İzinleri Ver
      run: chmod +x gradlew

    - name: APK Derle
      run: ./gradlew assembleDebug --stacktrace
      
    - name: APK Yükle
      uses: actions/upload-artifact@v3
      with:
        name: vpn-uygulamasi
        path: app/build/outputs/apk/debug/app-debug.apk
