name: Android Build

on:
  push:
    branches: [ "master" ] # Bu projede ana dal "master" olabilir, kontrol et
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Java Kurulumu (JDK 17)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle İzinleri
      run: chmod +x gradlew
      
    - name: APK Derle
      run: ./gradlew assembleDebug --stacktrace
      
    - name: APK Yükle
      uses: actions/upload-artifact@v3
      with:
        name: vpn-uygulamasi
        path: app/build/outputs/apk/debug/app-debug.apk
